Virtual check-in
cabeese/greatpuzzlehunt pull request #49
Opened 2021-02-20 23:26 UTC by cabeese

Update team check-in page to not require a volunteer to scan the QR code of a team. We will remove this functionality for in-person events.

2021-03-23 19:14 UTC, RvanB commented on client/components/TeamCheckin/imports/TeamCheckInVirtually.jsx
> +          modalContent: `You may procede to the game page`
Typo, should be "proceed"

2021-03-23 19:21 UTC, RvanB requested changes
Fix typo above, rebase with master before merging. Worked really well!

2021-03-24 13:28 UTC, cabeese commented on client/components/TeamCheckin/imports/TeamCheckInVirtually.jsx
> +          modalContent: `You may procede to the game page`
fixed, ty!

2021-03-24 13:30 UTC, cabeese commented
@RvanB thanks for testing and the comments. I pushed up the grammar fix. I also decided to drop the commit that would enforce team leaders to be checked in since we no longer lock down functionality for them. Ready for final review

2021-03-25 02:40 UTC, RvanB approved these changes

2021-03-25 02:41 UTC, merged