Feature/virtual gameplay
cabeese/greatpuzzlehunt pull request #51
Opened 2021-03-07 17:30 UTC by cabeese

Add virtual gameplay features, including ability to upload a PDF of the puzzle in the admin page and the ability to download that PDF as a player on the team.

2021-03-15 00:10 UTC, cabeese commented
Note - will change so that ANY player can start the puzzle. The puzzles will be in a set order for the virtual hunt so there isn't a worry about race conditions

2021-03-15 21:47 UTC, cabeese commented
Updated so that any player can start. ready for review

2021-03-23 19:56 UTC, RvanB requested changes
[
![image](https://user-images.githubusercontent.com/32312368/112209694-f5eacc80-8bd6-11eb-9eeb-b56eb74d3c24.png)
](url)

"Head back to Red Square" should be removed (probably commented out).

Played through several games with different users and teams, and couldn't break anything! Awesome work!

2021-03-24 19:30 UTC, RvanB approved these changes

2021-03-25 00:28 UTC, merged