Registration process rewording
cabeese/greatpuzzlehunt pull request #7
Opened 2019-11-23 21:46 UTC by RvanB

2019-11-24 15:37 UTC, cabeese requested changes
Changes here look good. I think we still need to update the instructions in the verification email to match the new phrasing we're adopting this year. Check out `lib/imports/emails.js` and `lib/imports/sendTickets.js` (I think only the former of the two will need to be changed).

2019-11-24 15:37 UTC, cabeese commented on client/components/public/FAQ.jsx
> +        <p>Last Updated: January 2020</p>
Isn't it November 2019 right now? ;)

2019-11-24 15:44 UTC, cabeese commented
While you're at it, would you fix the typo on `emails.js:14` where "invitation" is misspelled "invitiation"? I don't want to fix it myself and create merge conflicts. TY!

2019-11-24 23:09 UTC, cabeese requested changes

2019-11-24 23:09 UTC, cabeese commented on lib/imports/emails.js
> +      Verify your email before continuing.
Could you add a `<br />` at the end of this line?

2019-11-24 23:09 UTC, cabeese commented on lib/imports/emails.js
> +      Ticket code(s) will be sent to your email.
`<br />` at end

2019-11-24 23:09 UTC, cabeese commented on lib/imports/emails.js
> +      Set-up/join team at <a target="_blank" href="http://greatpuzzlehunt.com/team">${siteURL}/team</a>.<br/>
Replace the URL with `${siteURL}` for consistency (also b/c https)

2019-12-01 19:32 UTC, cabeese approved these changes
Awesome, @RvanB. Were you able to send a test email and at least see its content in the console log to ensure the email was formatted as expected after your changes?

2019-12-01 21:16 UTC, RvanB commented
Yeah I created a new account to see what the verification email looks like, looks good in the logs!

2019-12-01 21:17 UTC, merged